Recrutement/Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WebApplication1.Models;

namespace Recrutement.Models
{
    public class Job
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Nom du travail")]
        public  String JobTitle { get; set; }
        [Required]
        [Display(Name = "Description du travail")]
        public String JobContent { get; set; }

        [Display(Name = "Image ")]
        public String JobImage { get; set; }

        [Display(Name = "Type du travail ")]
        public int CategoryId { get; set; }
        [Display(Name = "Type du travail ")]
        public virtual Categorie Category { get; set; }

        public string  UserId { get; set; }

        public virtual ApplicationUser User { get; set; }

        public virtual ICollection<ApplyForJob> ApplyJobs { get; set; }

    }
}

Recrutement/Models/JobsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Recrutement.Models
{
    public class JobsViewModel
    {
        public string JobTitle { get; set; }
        public IEnumerable<ApplyForJob> Elements { get; set; }
    }
}

Recrutement/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Recrutement.Models;
using WebApplication1.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace Recrutement.Controllers
{
    [Authorize/*(Roles = "Entreprise")*/]
    public class JobsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jobs
        public ActionResult Index()
        {
            var UserId = User.Identity.GetUserId();

            var jobs = db.Jobs.Include(j => j.Category).Where(a=>a.UserId==UserId);
            return View(jobs.ToList());
        }

        // GET: Jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Jobs/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName");
            return View();
        }

        // POST: Jobs/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Job job,HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                //telecharger la photo sur le serveur et stocker son chemin dans la base de donnee
                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                job.JobImage = upload.FileName;
                job.UserId = User.Identity.GetUserId();
                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryId);
            return View(job);
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryId);
            return View(job);
        }

        // POST: Jobs/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Job job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                //telecharger la photo sur le serveur et stocker son chemin dans la base de donnee
                string oldPath = Path.Combine(Server.MapPath("~/Uploads"), job.JobImage);

                if(upload != null)
                {
                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                    upload.SaveAs(path);
                    job.JobImage = upload.FileName;

                }
                
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "CategoryName", job.CategoryId);
            return View(job);
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Recrutement/Views/Jobs/Create.cshtml
@model Recrutement.Models.Job

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/shared/_MainLayout.cshtml";
}

<h2 class="alert alert-info">Créer une Offre</h2>

@using (Html.BeginForm("Create", "Jobs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Titre de l'offre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Image :", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload"/>
                @Html.ValidationMessageFor(model => model.JobImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Secteur de l'offre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer" class="btn btn-success" />
                @Html.ActionLink("Annuler", "Index", null, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

Recrutement/Views/Jobs/Delete.cshtml
@model Recrutement.Models.Job

@{
    ViewBag.Title = "Supprimer";
    Layout = "~/Views/shared/_MainLayout.cshtml";
}


<h3 class="alert alert-danger">Voulez-vous vraiment supprimer cela?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt >
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.JobImage)" class="thumbnail center-block" style="width:48px;height:48px;" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-danger" /> 
            @Html.ActionLink("Retour à la liste", "Index" ,null, new {@class="btn btn-warning" })
        </div>
    }
</div>

Recrutement/Views/Jobs/Details.cshtml
@model Recrutement.Models.Job

@{
    ViewBag.Title = "Détails";
    Layout = "~/Views/shared/_MainLayout.cshtml";
}

<h2 class="alert alert-info">Détails</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.JobContent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.JobContent)
        </dd>
        <hr />
        <dt>
            @Html.DisplayNameFor(model => model.JobImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.JobImage)" class="thumbnail center-block" style="width:48px;height:48px;" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.Id }, new { @class = "btn btn-success" }) 
    @Html.ActionLink("Back to List", "Index",null,new { @class = "btn btn-danger" })
</p>

Recrutement/Views/Jobs/Edit.cshtml
@model Recrutement.Models.Job

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/shared/_MainLayout.cshtml";
}

<h2 class="alert alert-info">Modifier l'offre</h2>

@using (Html.BeginForm("Edit", "Jobs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()



<div class="form-horizontal">
    <div class="alert alert-danger" id="error-div" style="display:none">
        <span id="view-err"></span>
    </div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.JobImage)

    <div class="form-group">
        @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JobContent, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.JobContent, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.JobContent, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.JobImage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="upload" id="image" />
            @Html.ValidationMessageFor(model => model.JobImage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Modifier" class="btn btn-success" id="modifier" />
            @Html.ActionLink("Retour à la liste", "Index",null,new { @class="btn btn-danger" })
        </div>
    </div>
</div>
}


@section scripts{
    <script>
        $(function () {
            $("#modifier").click(function () {
                
                if ($("#image").val() != "") {
                    //check if the image extension is valid
                    var filename = $("#image").val();
                    var extensionImg = filename.substr(filename.lastIndexOf('.') + 1).toLowerCase();
                    var validExtensions = ['jpg', 'png', 'gif', 'bmp'];
                    if ($.inArray(extensionImg, validExtensions) == -1) {
                        $("#error-div").fadeIn();
                        $("#view-err").text("le fichier doit être une image [jpg,png,gif,bmp]");
                        return false;
                    }

                    //check if the image size

                    var myFileSize = document.getElementById("#image").files[0].size / (1024 * 1024);

                    if (myFileSize > 2) {
                        $("#error-div").fadeIn();
                        $("#view-err").text("le size de l'image doit être inferieur à 2mo");
                        return false;
                    }
                }

            });

            

        })
    </script>
}

Recrutement/Views/Jobs/Index.cshtml
@model IEnumerable<Recrutement.Models.Job>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/_MainLayout.cshtml";
}

<h2 class="alert alert-info">Liste De Mes Offres</h2>

<p>
    @Html.ActionLink("Ajouter Une Nouvelle ", "Create",null,new {@class="btn btn-info"})
</p>
<table class="table table-bordered table-hover table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobImage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobContent)
        </td>
        <td>
            <img src="~/Uploads/@Html.DisplayFor(modelItem => item.JobImage)" class="thumbnail center-block" style="width:48px;height:48px;" />
        </td>
        <td>
            @Html.ActionLink("Modifier", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" })
            @Html.ActionLink("Détails", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Supprimer", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>